# name: Build Android APK

# on:
#   push:
#     branches: [ master ]
#   workflow_dispatch:

# permissions:
#   contents: write

# jobs:
#   build-apk:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v4

#       - name: Setup Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           channel: stable

#       - name: Install dependencies
#         run: |
#           flutter clean
#           flutter pub get

#       - name: Build release APK
#         run: flutter build apk --release

#       - name: Upload APK artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: app-release-apk
#           # Đã sửa path cho đúng cấu trúc root của bạn
#           path: build/app/outputs/flutter-apk/app-release.apk

#       - name: Create GitHub Release
#         if: github.ref == 'refs/heads/master'
#         uses: softprops/action-gh-release@v2
#         with:
#           tag_name: v1.0.${{ github.run_number }}
#           name: "Build #${{ github.run_number }}"
#           # Đã sửa path cho đúng cấu trúc root của bạn
#           files: build/app/outputs/flutter-apk/app-release.apk
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}